apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: albiondata-deduper
  namespace: albiondata
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: albiondata-deduper
    spec:
      containers:
        - name: albiondata-deduper
          image: us.gcr.io/personal-projects-1369/albiondata/deduper:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 30m
              memory: 250Mi
          args:
            - -n $(NATS_URL)
            - -r $(REDIS_ADDR)
            - -p $(REDIS_PASS)
          env:
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats
                  key: nats_url
            - name: REDIS_ADDR
              value: ad-redis-redis:6379
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: ad-redis-redis
                  key: redis-password